### ISSUE TITLE
Build and Rebuild are broken in current Jenkins LTS

### ISSUE THREAD

**Issue by benken-parasoft** [i-m-c/jenkins-inheritance-plugin#61]
After updating to the current Jenkins LTS 2.479.1 (October 30, 2024) the Inheritance Plugin is almost unusable.

Clicking Build results in an error page with the following NoSuchMethodError logged:
```
java.lang.NoSuchMethodError: 'void hudson.model.ParametersDefinitionProperty._doBuild(org.kohsuke.stapler.StaplerRequest, org.kohsuke.stapler.StaplerResponse, jenkins.util.TimeDuration)'
	at PluginClassLoader for project-inheritance//hudson.plugins.project_inheritance.projects.InheritanceProject.doBuildInternal(InheritanceProject.java:1857)
	at PluginClassLoader for project-inheritance//hudson.plugins.project_inheritance.projects.InheritanceProject.doBuild(InheritanceProject.java:1801)
	at jenkins.model.ParameterizedJobMixIn$ParameterizedJob.doBuild(ParameterizedJobMixIn.java:411)
	at java.base/java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:733)
	at org.kohsuke.stapler.Function$MethodFunction.invoke(Function.java:484)
```

Clicking Rebuild (Rebuilder Plugin) results in an error page with the following JellyTagExceptions logged:
```
org.apache.commons.jelly.JellyTagException: jar:file:/opt/jenkins/war/WEB-INF/lib/jenkins-core-2.479.1.jar!/lib/layout/layout.jelly:206:24: <d:invokeBody>
org.apache.commons.jelly.JellyTagException: jar:file:/opt/jenkins/war/WEB-INF/lib/jenkins-core-2.479.1.jar!/lib/layout/main-panel.jelly:62:21: <d:invokeBody>
org.apache.commons.jelly.JellyTagException: jar:file:/opt/jenkins/war/WEB-INF/lib/jenkins-core-2.479.1.jar!/lib/form/form.jelly:67:22: <d:invokeBody>
org.apache.commons.jelly.JellyTagException: jar:file:/opt/jenkins/war/WEB-INF/lib/jenkins-core-2.479.1.jar!/lib/form/block.jelly:32:22: <d:invokeBody>
No signature of method: hudson.plugins.project_inheritance.projects.rebuild.InheritanceRebuildAction.getParametersFor() is applicable for argument types: (org.kohsuke.stapler.RequestImpl, java.lang.Boolean) values: [org.kohsuke.stapler.RequestImpl@7ad3e318, false]
Possible solutions: getParametersFor(org.kohsuke.stapler.StaplerRequest, java.lang.Boolean), getParametersFor(org.kohsuke.stapler.StaplerRequest)
	at org.apache.commons.jelly.impl.TagScript.handleException(TagScript.java:725)
```

However, we can still trigger such jobs from an upstream job using "Triggger/call builds on other projects".
Prior to this, I was using either Jenkins LTS 2.462 or 2.452.

**Comment by therewillbeblood** [comment]
Thanks for reporting this! @HedAurabesh you are no longer maintaining this plugin i assume ?

**Comment by ErezD1** [comment]
this is quit frustrating actually. we use this plugin alot and it completly breaks our jenkins in the latest LTS.
